name: senkyo
main: senkyo\senkyo
version: 0.2.0
api: [1.11.0]
load: POSTWORLD
author: soradore
description: touhyou senkyo plugin
commands:
 senkyo:
  description: "選挙を開始、終了します"
  permission: "senkyo.cmd"
  
 rikkouho:
  description: "立候補します"

 touhyou:
  description: "投票します"

 rhs:
  description: "立候補者一覧"

 delall:
  description: "選挙のデータすべてを削除します"
  permission: "delall.cmd"
permissions:
 senkyo.cmd:
  default: op
 delall.cmd:
  default: op